name: ai
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - alsa-lib=1.2.14=hb9d3cd8_0
  - aom=3.6.0=h6a678d5_0
  - blas=1.0=mkl
  - brotli-python=1.0.9=py313h6a678d5_9
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hef5626c_0
  - ca-certificates=2025.9.9=h06a4308_0
  - cairo=1.18.4=h44eff21_0
  - contourpy=1.3.1=py313hdb19cb5_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h1110e0f_3
  - dav1d=1.2.1=h5eee18b_0
  - dbus=1.16.2=h5bd4931_0
  - expat=2.7.1=h6a678d5_0
  - fontconfig=2.14.1=h55d465d_3
  - fonttools=4.55.3=py313h5eee18b_0
  - freetype=2.13.3=h4a9f257_0
  - fribidi=1.0.10=h7b6447c_0
  - glib=2.84.2=h6a678d5_0
  - glib-tools=2.84.2=h6a678d5_0
  - graphite2=1.3.14=h295c915_1
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - harfbuzz=10.2.0=hdfddeaa_1
  - icu=73.1=h6a678d5_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jack=1.9.22=hf4617a5_3
  - jpeg=9f=h5ce9db8_0
  - kiwisolver=1.4.8=py313h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lcms2=2.16=h92b89f2_1
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20250127.0=cxx17_h6a678d5_0
  - libavif=1.1.1=h5eee18b_0
  - libclang=14.0.6=default_hc6dbbc7_2
  - libclang13=14.0.6=default_he11475f_2
  - libcups=2.4.2=h252cb56_2
  - libcurl=8.15.0=hc1efc7f_0
  - libdeflate=1.22=h5eee18b_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.1.0=h767d61c_5
  - libgcc-ng=15.1.0=h69a702a_5
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.84.2=h37c7471_0
  - libgomp=15.1.0=h767d61c_5
  - libiconv=1.16=h5eee18b_3
  - libkrb5=1.21.3=h520c7b4_4
  - libllvm14=14.0.6=hecde1de_4
  - libmpdec=4.0.0=h5eee18b_0
  - libnghttp2=1.57.0=h2d74bed_0
  - libopus=1.5.2=hd0c01bc_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=17.4=h02b6914_2
  - libprotobuf=5.29.3=h3cdef7c_1
  - libsodium=1.0.18=h7b6447c_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx=15.1.0=h8f9b012_5
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.7.0=hde9077f_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h9b100fa_0
  - libxkbcommon=1.9.1=h69220b7_0
  - libxml2=2.13.8=hfdd30dd_0
  - lmdb=0.9.31=hb25bd0a_0
  - lz4-c=1.9.4=h6a678d5_1
  - matplotlib=3.10.5=py313h06a4308_0
  - matplotlib-base=3.10.5=py313he37261f_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py313h5eee18b_2
  - mkl_fft=1.3.11=py313h5eee18b_0
  - mkl_random=1.2.8=py313h06d7b56_0
  - mysql=8.4.0=h721767e_2
  - ncurses=6.5=h7934f7d_0
  - numpy-base=2.1.3=py313h3fc9231_0
  - openjpeg=2.5.2=h0d4d230_1
  - openldap=2.6.10=h8e75217_0
  - openssl=3.0.18=hd6dcaed_0
  - packaging=25.0=py313h06a4308_0
  - pcre2=10.42=hebb0a14_1
  - pillow=11.3.0=py313hb1c3d2d_0
  - pip=25.2=pyhc872135_0
  - pixman=0.46.4=h7934f7d_0
  - ply=3.11=py313h06a4308_1
  - portaudio=19.7.0=hf4617a5_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pyaudio=0.2.14=py313h5f52a73_3
  - pyparsing=3.2.0=py313h06a4308_0
  - pyqt=5.15.10=py313h6a678d5_1
  - pyqt5-sip=12.13.0=py313h5eee18b_1
  - python=3.13.7=h7e8bc2b_100_cp313
  - python-dateutil=2.9.0post0=py313h06a4308_2
  - python_abi=3.13=1_cp313
  - qt-main=5.15.2=hb6262e9_12
  - readline=8.3=hc2a1206_0
  - scipy=1.15.3=py313h7f54423_0
  - setuptools=72.1.0=py313h06a4308_0
  - sip=6.7.12=py313h6a678d5_1
  - six=1.17.0=py313h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.45.1=py313h06a4308_0
  - xkeyboard-config=2.44=h5eee18b_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=hd233ad5_2
  - zstd=1.5.6=hc292b87_0
  - pip:
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - aisecretary-backend==0.1.0
      - alembic==1.17.1
      - annotated-types==0.7.0
      - anyio==4.10.0
      - asyncpg==0.30.0
      - attrs==25.3.0
      - audioop-lts==0.2.2
      - bcrypt==4.3.0
      - brotli==1.1.0
      - certifi==2025.8.3
      - cffi==2.0.0
      - charset-normalizer==3.4.3
      - click==8.1.8
      - cryptography==45.0.7
      - deepseek==1.0.0
      - distro==1.9.0
      - ecdsa==0.19.1
      - fastapi==0.117.1
      - ffmpy==0.6.1
      - filelock==3.19.1
      - frozenlist==1.7.0
      - fsspec==2025.9.0
      - gradio==5.46.1
      - gradio-client==1.13.1
      - greenlet==3.2.4
      - groovy==0.1.2
      - groq==0.31.1
      - gtts==2.5.4
      - h11==0.16.0
      - hf-xet==1.1.10
      - http-ece==1.2.1
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.35.0
      - idna==3.10
      - jieba==0.42.1
      - jinja2==3.1.6
      - jiter==0.10.0
      - llvmlite==0.44.0
      - mako==1.3.10
      - markdown-it-py==4.0.0
      - markupsafe==3.0.2
      - mdurl==0.1.2
      - more-itertools==10.8.0
      - mpmath==1.3.0
      - multidict==6.6.4
      - networkx==3.5
      - numba==0.61.2
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.8.90
      - openai==1.107.0
      - openai-whisper==20250625
      - opencc==1.1.9
      - opencc-python-reimplemented==0.1.7
      - orjson==3.11.3
      - pandas==2.3.2
      - passlib==1.7.4
      - pillow-heif==1.1.0
      - propcache==0.3.2
      - psycopg==3.2.3
      - psycopg-binary==3.2.3
      - psycopg2-binary==2.9.9
      - py-vapid==1.9.2
      - pyasn1==0.6.1
      - pycantonese==3.4.0
      - pycparser==2.23
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pydantic-settings==2.11.0
      - pydub==0.25.1
      - pygame==2.6.1
      - pygments==2.19.2
      - pyjwt==2.10.1
      - pylangacq==0.16.2
      - pypinyin==0.55.0
      - python-dotenv==1.2.1
      - python-jose==3.5.0
      - python-multipart==0.0.20
      - pytz==2025.2
      - pywebpush==2.0.3
      - pyyaml==6.0.2
      - regex==2025.9.1
      - requests==2.32.5
      - rich==14.1.0
      - rsa==4.9.1
      - ruff==0.13.1
      - safehttpx==0.1.6
      - semantic-version==2.10.0
      - shellingham==1.5.4
      - sniffio==1.3.1
      - sounddevice==0.5.2
      - soundfile==0.13.1
      - sqlalchemy==2.0.44
      - starlette==0.48.0
      - stripe==7.9.0
      - structlog==25.5.0
      - sympy==1.14.0
      - tabulate==0.9.0
      - tiktoken==0.11.0
      - tomlkit==0.13.3
      - torch==2.8.0
      - torchaudio==2.8.0
      - tornado==6.5.2
      - tqdm==4.67.1
      - triton==3.4.0
      - typer==0.19.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - urllib3==2.5.0
      - uvicorn==0.36.0
      - wcwidth==0.2.13
      - websockets==15.0.1
      - whisper==1.1.10
      - wordseg==0.0.2
      - yarl==1.20.1
prefix: /home/lachlan/miniconda3/envs/ai
